vars:
  - dataset:
      year: '2019'

stages:
  merge_lcfa_2019:
    cmd: 
      - julia scripts/dataset/merge_lcfa.jl ../GLM-L2-LCFA/2019
    deps:
      - scripts/dataset/merge_lcfa.jl
      - src/dataset/l2_lcfa_merge.jl
      - src/structs/FlashRecords.jl
    outs:
      - data/exp_pro/GLM-L2-LCFA/2019.jld2:
          persist: true
          cache: true

  merge_lcfa_2020:
    cmd: 
      - julia scripts/dataset/merge_lcfa.jl ../GLM-L2-LCFA/2020
    deps:
      - scripts/dataset/merge_lcfa.jl
      - src/dataset/l2_lcfa_merge.jl
      - src/structs/FlashRecords.jl
    outs:
      - data/exp_pro/GLM-L2-LCFA/2020.jld2:
          persist: true
          cache: true

  merge_lcfa_2021:
    cmd: 
      - julia scripts/dataset/merge_lcfa.jl ../GLM-L2-LCFA/2021
    deps:
      - scripts/dataset/merge_lcfa.jl
      - src/dataset/l2_lcfa_merge.jl
      - src/structs/FlashRecords.jl
    outs:
      - data/exp_pro/GLM-L2-LCFA/2021.jld2:
          persist: true
          cache: true

  grid_dataset:
    cmd:
      - julia scripts/dataset/grid_fed.jl -s ${ds.resolution.spatial} -t ${ds.resolution.temporal} -f data/exp_pro/GLM-L2-LCFA/${dataset.year}.jld2
    deps:
      - scripts/dataset/grid_fed.jl
      - src/dataset/fed_grid.jl
      - src/dataset/l2_lcfa_merge.jl
      - data/exp_pro/GLM-L2-LCFA/2019.jld2
      - data/exp_pro/GLM-L2-LCFA/2020.jld2
      - data/exp_pro/GLM-L2-LCFA/2021.jld2
    outs:
      - data/exp_pro/GLM-L2-LCFA-GRID/spatial=${ds.resolution.spatial}_temporal=${ds.resolution.temporal}_year=${dataset.year}:
          persist: true
          cache: true
    params:
      - ds.resolution.spatial
      - ds.resolution.temporal

