vars:
  - dataset:
      year: '2020'

stages:
  merge_lcfa:
    cmd: julia scripts/dataset/merge_lcfa.jl ../GLM-L2-LCFA/${dataset.year}
    deps:
      - scripts/dataset/merge_lcfa.jl
      - src/dataset/l2_lcfa_merge.jl
      - src/structs/FlashRecords.jl
    outs:
      - data/exp_pro/GLM-L2-LCFA/${dataset.year}.jld2:
          persist: true
