ds:
  resolution:
    spatial: 4
    temporal: 15
  cluster:
    threshold: 1.0
    radius: 3.0
    min_neighbors: 50
    min_cluster_size: 100
    t_scale: 2.0
    windows: 5,5,10
    dimensions: 64,64,20
    padding: 2,2,4
train:
  ds: # Dataset
    type: SequenceFED
    splitratio: 0.8
    batchsize: 8
    N: 10
  arch: # Architecture
    type: EncoderForecaster05.2.2
    out: 10
    dropout: 0.25
  optimiser: RMSProp(0.0003)
  epochs: 100
  loss: logcsi
gpu:
  CUDA_VISIBLE_DEVICES: 0


