name = "NowcastingHuascaran"
authors = ["Marco Vela"]

[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"

[compat]
DrWatson = "2.2.1"
julia = "1.6.1"
